//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonWay.WebServiceConnector.XmlToJsonWSRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReponseOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WebServiceReponseOfString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LemonWay.WebServiceConnector.XmlToJsonWSRef.ReponseMessage[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public LemonWay.WebServiceConnector.XmlToJsonWSRef.ReponseMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReponseMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ReponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LemonWay.WebServiceConnector.XmlToJsonWSRef.MessageType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LemonWay.WebServiceConnector.XmlToJsonWSRef.MessageType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://tempuri.org/")]
    public enum MessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XmlToJsonWSRef.XmlToJsonWebServiceSoap")]
    public interface XmlToJsonWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name xmlStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponse XmlToJson(LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponse> XmlToJsonAsync(LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJson", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequestBody Body;
        
        public XmlToJsonRequest() {
        }
        
        public XmlToJsonRequest(LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlStr;
        
        public XmlToJsonRequestBody() {
        }
        
        public XmlToJsonRequestBody(string xmlStr) {
            this.xmlStr = xmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlToJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponseBody Body;
        
        public XmlToJsonResponse() {
        }
        
        public XmlToJsonResponse(LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LemonWay.WebServiceConnector.XmlToJsonWSRef.WebServiceReponseOfString XmlToJsonResult;
        
        public XmlToJsonResponseBody() {
        }
        
        public XmlToJsonResponseBody(LemonWay.WebServiceConnector.XmlToJsonWSRef.WebServiceReponseOfString XmlToJsonResult) {
            this.XmlToJsonResult = XmlToJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XmlToJsonWebServiceSoapChannel : LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XmlToJsonWebServiceSoapClient : System.ServiceModel.ClientBase<LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonWebServiceSoap>, LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonWebServiceSoap {
        
        public XmlToJsonWebServiceSoapClient() {
        }
        
        public XmlToJsonWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XmlToJsonWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlToJsonWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XmlToJsonWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponse LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonWebServiceSoap.XmlToJson(LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest request) {
            return base.Channel.XmlToJson(request);
        }
        
        public LemonWay.WebServiceConnector.XmlToJsonWSRef.WebServiceReponseOfString XmlToJson(string xmlStr) {
            LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest inValue = new LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest();
            inValue.Body = new LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequestBody();
            inValue.Body.xmlStr = xmlStr;
            LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponse retVal = ((LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonWebServiceSoap)(this)).XmlToJson(inValue);
            return retVal.Body.XmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponse> LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonWebServiceSoap.XmlToJsonAsync(LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest request) {
            return base.Channel.XmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonResponse> XmlToJsonAsync(string xmlStr) {
            LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest inValue = new LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequest();
            inValue.Body = new LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonRequestBody();
            inValue.Body.xmlStr = xmlStr;
            return ((LemonWay.WebServiceConnector.XmlToJsonWSRef.XmlToJsonWebServiceSoap)(this)).XmlToJsonAsync(inValue);
        }
    }
}
