//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LemonWay.WebServiceConnector.FibonacciWSRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReponseOfInt32", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WebServiceReponseOfInt32 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LemonWay.WebServiceConnector.FibonacciWSRef.ReponseMessage[] MessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.ReponseMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReponseMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ReponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LemonWay.WebServiceConnector.FibonacciWSRef.MessageType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.MessageType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://tempuri.org/")]
    public enum MessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FibonacciWSRef.FibonacciWebserviceSoap")]
    public interface FibonacciWebserviceSoap {
        
        // CODEGEN: Generating message contract since element name ComputeFibonacciResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComputeFibonacci", ReplyAction="*")]
        LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponse ComputeFibonacci(LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ComputeFibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponse> ComputeFibonacciAsync(LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest request);
        
        // CODEGEN: Generating message contract since element name DivisionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponse Division(LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponse> DivisionAsync(LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComputeFibonacciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComputeFibonacci", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequestBody Body;
        
        public ComputeFibonacciRequest() {
        }
        
        public ComputeFibonacciRequest(LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComputeFibonacciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int number;
        
        public ComputeFibonacciRequestBody() {
        }
        
        public ComputeFibonacciRequestBody(int number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComputeFibonacciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ComputeFibonacciResponse", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponseBody Body;
        
        public ComputeFibonacciResponse() {
        }
        
        public ComputeFibonacciResponse(LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ComputeFibonacciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.WebServiceReponseOfInt32 ComputeFibonacciResult;
        
        public ComputeFibonacciResponseBody() {
        }
        
        public ComputeFibonacciResponseBody(LemonWay.WebServiceConnector.FibonacciWSRef.WebServiceReponseOfInt32 ComputeFibonacciResult) {
            this.ComputeFibonacciResult = ComputeFibonacciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Division", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequestBody Body;
        
        public DivisionRequest() {
        }
        
        public DivisionRequest(LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int number1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int number2;
        
        public DivisionRequestBody() {
        }
        
        public DivisionRequestBody(int number1, int number2) {
            this.number1 = number1;
            this.number2 = number2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponseBody Body;
        
        public DivisionResponse() {
        }
        
        public DivisionResponse(LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LemonWay.WebServiceConnector.FibonacciWSRef.WebServiceReponseOfInt32 DivisionResult;
        
        public DivisionResponseBody() {
        }
        
        public DivisionResponseBody(LemonWay.WebServiceConnector.FibonacciWSRef.WebServiceReponseOfInt32 DivisionResult) {
            this.DivisionResult = DivisionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FibonacciWebserviceSoapChannel : LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FibonacciWebserviceSoapClient : System.ServiceModel.ClientBase<LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap>, LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap {
        
        public FibonacciWebserviceSoapClient() {
        }
        
        public FibonacciWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FibonacciWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FibonacciWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FibonacciWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponse LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap.ComputeFibonacci(LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest request) {
            return base.Channel.ComputeFibonacci(request);
        }
        
        public LemonWay.WebServiceConnector.FibonacciWSRef.WebServiceReponseOfInt32 ComputeFibonacci(int number) {
            LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest inValue = new LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest();
            inValue.Body = new LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequestBody();
            inValue.Body.number = number;
            LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponse retVal = ((LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap)(this)).ComputeFibonacci(inValue);
            return retVal.Body.ComputeFibonacciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponse> LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap.ComputeFibonacciAsync(LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest request) {
            return base.Channel.ComputeFibonacciAsync(request);
        }
        
        public System.Threading.Tasks.Task<LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciResponse> ComputeFibonacciAsync(int number) {
            LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest inValue = new LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequest();
            inValue.Body = new LemonWay.WebServiceConnector.FibonacciWSRef.ComputeFibonacciRequestBody();
            inValue.Body.number = number;
            return ((LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap)(this)).ComputeFibonacciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponse LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap.Division(LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest request) {
            return base.Channel.Division(request);
        }
        
        public LemonWay.WebServiceConnector.FibonacciWSRef.WebServiceReponseOfInt32 Division(int number1, int number2) {
            LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest inValue = new LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest();
            inValue.Body = new LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponse retVal = ((LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap)(this)).Division(inValue);
            return retVal.Body.DivisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponse> LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap.DivisionAsync(LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest request) {
            return base.Channel.DivisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<LemonWay.WebServiceConnector.FibonacciWSRef.DivisionResponse> DivisionAsync(int number1, int number2) {
            LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest inValue = new LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequest();
            inValue.Body = new LemonWay.WebServiceConnector.FibonacciWSRef.DivisionRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            return ((LemonWay.WebServiceConnector.FibonacciWSRef.FibonacciWebserviceSoap)(this)).DivisionAsync(inValue);
        }
    }
}
